### ISSUE TITLE
 bug: Could not interpret as TeX input

### ISSUE THREAD

**Issue by raverydavis** [jfultz/Chatbook#53] opened 2023-04-24 01:15 UTC
<img width="741" alt="image" src="https://user-images.githubusercontent.com/10748455/233878489-513742c1-f876-45c5-9986-afaaca6dd4d9.png">

<details>
<summary>Cell data</summary>

Raw data
```
Cell[TextData[{
 "You have an arithmetic expression which consists of subtraction and multiplication operations. The \
expression can be read as: \"subtract 5 from 13, and then multiply the result by 2\". Let's break it \
down step by step:\n\n1. Subtract 5 from 13: ",
 Cell[BoxData[
  FormBox[
   TemplateBox[<|"boxes" -> InterpretationBox["", 
       Failure[
       "TeXAssistantError", <|
        "MessageTemplate" -> "Errors: `Errors`", "MessageParameters" -> <|"Errors" -> {}|>, "Input" -> 
         "13 - 5 = 8"|>]], "errors" -> {}, "input" -> "13 - 5 = 8", "state" -> "Error"|>,
    "TeXAssistantTemplate"], TraditionalForm]]],
 "\n2. Multiply the result by 2: ",
 Cell[BoxData[
  FormBox[
   TemplateBox[<|"boxes" -> FormBox[
       RowBox[{"8*2", "\[LongEqual]", "16"}], TraditionalForm], "errors" -> {}, "input" -> 
     "8 * 2 = 16", "state" -> "Boxes"|>,
    "TeXAssistantTemplate"], TraditionalForm]]],
 "\nSo, the result of the expression ",
 Cell[BoxData[
  FormBox[
   TemplateBox[<|"boxes" -> FormBox[
       RowBox[{
         RowBox[{"(", 
           RowBox[{"13", "-", "5"}], ")"}], "*2"}], TraditionalForm], "errors" -> {}, "input" -> 
     "(13 - 5) * 2", "state" -> "Boxes"|>,
    "TeXAssistantTemplate"], TraditionalForm]]],
 " is ",
 Cell[BoxData[
  FormBox[
   TemplateBox[<|
    "boxes" -> FormBox["16", TraditionalForm], "errors" -> {}, "input" -> "16", "state" -> "Boxes"|>,
    "TeXAssistantTemplate"], TraditionalForm]]],
 "."
}], "ChatOutput",
 TaggingRules-><|
  "CellToStringData" -> 
   "You have an arithmetic expression which consists of subtraction and multiplication operations. \
The expression can be read as: \"subtract 5 from 13, and then multiply the result by 2\". Let's break \
it down step by step:\n\n1. Subtract 5 from 13: $13 - 5 = 8$\n2. Multiply the result by 2: $8 * 2 = \
16$\n\nSo, the result of the expression $(13 - 5) * 2$ is $16$.", "MessageTag" -> "[INFO]", 
   "ChatData" -> 
   "OEM6eJylVt1uG0UUFiUtxKgqIG64G0okkmK7SkpRFalCVpqkEc6PsoZSRa06Xh97R56dWWZmnSxvAm/C43DDDS/\
Bd2ZtZ50AN0RRsjNz/s93vpnep52k1fNe+SBNSn69Vwaby6BS3sf3gXVY+rWBK6mTfLGXybBnTaCrsEdanzkLJa/\
M5KA0aVDWrFhoip9ZH/ZnUpeSxf5R/LOmuKPC2bwIyfMf2L6QIs2kMsKORchsOcmC8IEK3xZ0VWg+CRmJ0pP7yuNEBsrJhG4n+\
YStvkSC1lV9MpOQ7X2O3ReVkblKGzk2Q/n4wNHPJZm0OiMjdajcb7/yz+/fdZL1Y3k1sFMyfkXl/jG5CR2jHHKCP/\
OK3T22I9LJ3UkROt9A97Qg0zv6nqoV3QdI18Mb3fZ2P8ns5bEyKle/0GhF66MB5QU5GUpHbhx//\
oTG2sAWZ3vv4eOFDLKHjw8XUY3f92t9lKJ3B6fOakru+QplzDvJBykX3oTkrwf/q+\
Ct1sAKtG6mRsQ20GM4xImQZiRoPCY0fkZshJzinNui0CQ9ibHV2l6yWSwmJQxoZcjvtlpfikMyyFSLw+V2q/\
VIvHIqkEA5MrbnGIrwh6A4gb4c0E/Rqy+dsyU+YDoXlwriI/\
iSTng1MchobB0MyByB7IqNq7c74mtRvd3Z6MJHX5mpGCmHuHUlghWvrB47mcO+mZSoKmylJecekS2G1dw/l6dOiVe+\
gsDVrrjQckj6zWYhU01ht3RqqysOGv5bQjwSFwM51LSUcjR+HHe26tOl69MZuZmiy6VkLNvjxfnieK52ZIoyiCRGstQIAJRTUj+Op/\
XhFvIezLsrUmnQX6W18ESclXJCsWxbeMtrR0CAscIQjbhAGF2SQSj8GlHZ0mHHF2gMdZt21aJRclnSExtoaO0UigGQlil1xWs2kM8B\
LKQjtjoHIIgiBuFtzrXmMQ5sUZl6wf3IZSWGJDT4hzWDk8breNRlYO0DGk68BEyAqgni6/\
Vf9V4nUJncjL5GjjVUz0Szu0FOPKeuzEilGIV4HKoiii700fyjk4PTN21x8ap3fnJ0cohPOL/YPz8/PX/\
DxfnB16rzLba7YhatoBjw6vjFdqzoLxzcshDAhktVkUkvtJoSkJ3LOLA5XwVTDOWwrOVSEBgy5/ZHELjSxEJYnMdY/\
IrjmGH0ykMloWAZIssiROmjcTP66CGVWI2uE5x3vI2QEFA65caltOjmnGAi3NAjsanGQs6k0nFIeDcjXWBs5cTYeWggAHK6ivjwvqT\
Y/j32nZQTYCveR5FVMpANJudG95kggbo63vY1qQDnERghc5iPIWIFO099ZB5lUl2Oav96MbQx2KLQaAhHe2P83717d1mPQ4sd8Roxv\
cB42bC0h+Kj49z4RmEXZa0Pr+PtHDpZZCr1nTYHyz0fEoHZcxVCXUMvQcm+iAO3OvhI6Vp/broGB9cdIgirK072f9w/\
jxeDShXzJPMhT19D9+Y4RST0ZlYxQdcN4ElyagY2qkERwTqy5GPyVD8fiAOWpgoZ5LvXE5vKQgWpcU3epmhf5UOruXWuJvK22E/\
O9veOev3+a46M3bEtXMRjpJ5j6cAdBJyPvLCMhsIWJd8ZIAAvLhcYKSwuHbQxoumclXGncSK3YkjqGBYIE+6/hBcB3+\
KgmvMu48UXrzN0U2KGcUmhLCtXUVecGrRixCStoqlamWtZ59u6fgisccsbz4D1ze0novN069HOtcy6nL8UQ0PwjztgaIBqFtlJIrAM\
ZVNp40ZGtVSaLd4CnjnRl0Me6IgRHpS81EHFkYhbNr5reCBrPDZsMSrBAI4k2MLviocLU+\
KpGOPJKLaftKPJwEWe263iYMAElnxD7zzsij4FkM8QhqY8FiN7aeILh8/5P94d211ww03reCFwabDxXDzbaO10xfG/\
OIHkM9y7OxDc/naj1Upsuykyv0UauW1s1pa3WGuDb8gNKOIR25q/4AZyktyrOfZvBr8bvw=="|>,
 GeneratedCell->True,
 CellAutoOverwrite->True]
```

</details>

**Comment by rhennigan** [comment] 2023-04-24 10:45
I'm not able to reproduce this issue for that underlying string. @raverydavis, can you try evaluating the following to see if it reproduces the error:
```
Needs[ "Wolfram`Chatbook`" ];

CellPrint @ Cell[
    TextData @ Wolfram`Chatbook`Actions`Private`reformatTextData[ "You have an arithmetic expression which consists of subtraction and multiplication operations. The expression can be read as: \"subtract 5 from 13, and then multiply the result by 2\". Let's break it down step by step:\n\n1. Subtract 5 from 13: $13 - 5 = 8$\n2. Multiply the result by 2: $8 * 2 = 16$\n\nSo, the result of the expression $(13 - 5) * 2$ is $16$." ],
    "Text"
]
```

If that is pink-boxing, see if it's an issue with `TeXAssistant`:
```
InputAssistant`TeXAssistant[ "13 - 5 = 8" ]
```

**Comment by raverydavis** [comment] 2023-04-24 14:24
Yes, each of those are fine in 13.2.1 and 13.3

I did get other TeX in a different session that didn't give me an error - maybe this can be marked closed

**Comment by rhennigan** [comment] 2023-04-24 21:28
Closing for now. If it happens again, see if there's anything weird going on with ``InputAssistant`TeXAssistant`` and reopen as necessary.

**Closed by rhennigan** 2023-04-24 21:28 UTC
Labels: bug
